# .travis.yml
os: linux
dist: trusty
language: shell
addons:
  apt:
    packages:
    - lftp

branches:
  only:
  - master

install:
 - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.61.0/hugo_0.61.0_Linux-64bit.deb
 - sudo dpkg -i /tmp/hugo.deb

script:
 - hugo

deploy:
  - provider: script
    script: ./deploy.sh
    skip_cleanup: true
    on:
      branch: master
