# .travis.yml
os: linux
dist: trusty
language: shell
sudo: true
addons:
  apt:
    packages:
    - lftp

branches:
  only:
  - master

install:
 - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.61.0/hugo_0.61.0_Linux-64bit.deb
 - sudo dpkg -i /tmp/hugo.deb

script:
 - hugo
 - lftp ftp://$FTP_USER:$FTP_PASS@$FTP_HOST -e "set ssl:verify-certificate no;mirror -e -R public / ; quit"

deploy:
  - provider: script
    script: ./deploy.sh
    cleanup: true
    on:
      branch: master
