baseURL = "https://www.podlumiere.com/"
title = "Pod'lumière"
languageCode = "fr-FR"
theme = "podchaps"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
[outputs]
  home = ["html", "rss"]
  page = ["html"]
[author]
  name = "Podlumiere"
  email = "contact@podlumiere.com"