baseURL = "https://www.podlumiere.com/"
title = "Podlumiere"
theme = "podchaps"
languageCode = "fr-FR"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
googleAnalytics = "UA-154973610-1"
disqusShortname = "podlumiere"
  
[outputs]
  home = ["html", "rss"]
  page = ["html"]

[author]
  name = "Podlumiere"
  email = "contact@podlumiere.com"

[params]
  description = "Podlumière, le podcast ou y'a pas d'lumière" 
  subtitle = "De l'humour, de l'impro, mais pas d'lumière" 
  logo = "http://www.podlumiere.com/img/logo.png"
  keywords = "podlumiere, pod'lumiere, podlumière, pod'lumière, podcast, théâtre, humour, improvisation"
  footer = "Podlumiere - 2020"
  facebook = "https://www.facebook.com/podlumiere/"
  soundcloud = "https://soundcloud.com/podlumiere/"
  spotify = "https://open.spotify.com/show/7cj7Z21EH5XR10ODePtkFE"
  deezer = "https://www.deezer.com/fr/show/749702"
  apple = "https://podcasts.apple.com/fr/podcast/podlumiere/id1492585268"
