version: 1.0
jobs:
  build:
    machine:
      image: circleci/classic:latest
    branches:
      only:
        - master
    steps:
      - run:
          name: Install LFTP
          command: |
            sudo apt-get update;
            sudo apt-get install lftp;
      - checkout
      - run:
          name: Install Hugo
          command: |
            wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.68.1/hugo_0.68.1_Linux-64bit.deb
            sudo dpkg -i /tmp/hugo.deb
            hugo
      - run:
          name: Send Via FTP
          command: lftp ftp://${FTP_USER}:${FTP_PASS}@${FTP_HOST} -e "set ssl:verify-certificate no;mirror -e -R --parallel=8 public /; quit"
